plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.bellavision'
version = '0.1.0'

android {
  namespace "expo.modules.bellavision"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  // Cut-outs: runs in Google Play services, which downloads the model (see AndroidManifest.xml).
  implementation 'com.google.android.gms:play-services-mlkit-subject-segmentation:16.0.0-beta1'
}
